OriginalBondInfo<-list()
OriginalBondInfo$code.IB<-c("000000.IB")
OriginalBondInfo$issuedate<-c("2014/01/09")
OriginalBondInfo$maturitydate<-c("2021/01/09")
OriginalBondInfo$couponrate<-c(4.12)
OriginalBondInfo$frequency<-c(1)
BondInfo = InitGovBondInfo( OriginalBondInfo )
TFInfo<-list()
TFInfo$TFname<-c("TF1403")
TFInfo$LastTradeDate<-c(as.Date("2014-03-14"))
TFInfo$settlementMonth<-c(as.Date("2014-03-01"))
QuoteMoneyMarket_AllRepo<-c(5.24)
QuoteTF <- list()
QuoteTF$TF1403$date=c(as.Date("2014-01-09"))
QuoteTF$TF1403$close=c(0)
QuoteBond <- list()
QuoteBond[['000000.IB']]$date=c(as.Date("2014-01-09"))
QuoteBond[['000000.IB']]$YTM=c(4.12)
BondInfo = ResetToday(BondInfo,"GOV","2014-01-09",FALSE,FALSE,TRUE)
BondInfo = AddTFInfo(BondInfo,"GOV",TFInfo)
BondInfo = InitBondPrice(BondInfo,"GOV",QuoteBond)
BondInfo = InitTFPrice(BondInfo,"GOV",QuoteTF)
result1 = Calculate_BondPrice_from_TFPrice_repoVector(BondInfo,"GOV",TFInfo,QuoteMoneyMarket_AllRepo)
BondInfo = CalculateIRR(BondInfo,"GOV",TFInfo)
BondInfo = FindCTD(BondInfo,"GOV",TFInfo)
BondInfo = InitBPV(BondInfo,"GOV") 
result = CalculateRepoRelated(BondInfo,"GOV",TFInfo,QuoteMoneyMarket_AllRepo)